name: Feature Request
description: Suggest a new feature or enhancement for this package
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        Before filling out the issue fields, please consider the following:
        - Search for any [existing requests](https://github.com/cosee/alphabet_list_view/issues?q=is%3Aissue%20label%3A3Aenhancement).
        - Review the [guidelines for requesting a feature](https://github.com/cosee/alphabet_list_view/blob/main/CONTRIBUTING.md#request-a-feature) to ensure your request is clear and helpful.

  - type: textarea
    attributes:
      label: Description
      description: Describe your idea in detail. Explain its purpose, benefits, and how it could improve the package.
      placeholder: Tell us about your idea …
    validations:
      required: true
