// ignore_for_file: avoid-non-ascii-symbols

class Repository {
  Repository._();

  static const Map<String, List<String>> animals = {
    'A': [
      'Admiral, indian red',
      'African black crake',
      'African buffalo',
      'African clawless otter',
      'African ground squirrel (unidentified)',
      'African polecat',
      'African snake (unidentified)',
      'Albatross, galapagos',
      'Alligator, mississippi',
      'Alpaca',
      'American alligator',
      'American badger',
      'American beaver',
      'American black bear',
      'American racer',
      'American woodcock',
      'Ant (unidentified)',
      'Anteater, australian spiny',
      'Anteater, giant',
      'Antechinus, brown',
      'Antelope, roan',
      'Arboral spiny rat',
      'Arctic fox',
      'Arctic ground squirrel',
      'Arctic lemming',
      'Arctic tern',
      'Argalis',
      'Armadillo, common long-nosed',
      'Armadillo, nine-banded',
      'Asian lion',
      'Asian water buffalo',
      'Asiatic wild ass',
      'Ass, asiatic wild',
      'Australian brush turkey',
      'Australian magpie',
      'Australian masked owl',
      'Australian sea lion',
      "Azara's zorro",
    ],
    'B': [
      'Baboon, gelada',
      'Baboon, olive',
      'Baboon, savanna',
      'Baboon, yellow',
      'Baleen whale',
      'Bandicoot, short-nosed',
      'Bandicoot, southern brown',
      'Barasingha deer',
      'Barbet, black-collared',
      'Barrows goldeneye',
      'Bat, madagascar fruit',
      'Bear, black',
      'Beaver, north american',
      'Bee-eater, nubian',
      'Bengal vulture',
      'Bird, pied butcher',
      'Black bear',
      'Black-backed jackal',
      'Black-crowned crane',
      'Black-eyed bulbul',
      'Black-faced kangaroo',
      'Black-throated cardinal',
      'Blackbird, red-winged',
      'Blackbuck',
      'Blacksmith plover',
      'Blue peacock',
      'Blue wildebeest',
      'Blue-faced booby',
      'Boa, mexican',
      'Bobcat',
      'Bohor reedbuck',
      'Bontebok',
      'Brown brocket',
      'Brown pelican',
      'Brush-tailed bettong',
      'Brush-tailed phascogale',
      'Buffalo, american',
      'Bulbul, black-eyed',
      'Bulbul, black-fronted',
      'Burmese black mountain tortoise',
      'Burmese brown mountain tortoise',
      'Burrowing owl',
      'Bushbuck',
    ],
    'C': [
      'Caiman, spectacled',
      'Canada goose',
      'Cape Barren goose',
      'Cape raven',
      'Cape starling',
      'Cape white-eye',
      'Capuchin, brown',
      'Capuchin, weeper',
      'Capybara',
      'Cat, jungle',
      "Cat, miner's",
      'Cat, tiger',
      'Catfish, blue',
      'Cattle egret',
      'Chilean flamingo',
      'Chimpanzee',
      'Civet (unidentified)',
      'Civet, common palm',
      'Coatimundi, ring-tailed',
      'Coatimundi, white-nosed',
      'Cobra, cape',
      'Cobra, egyptian',
      'Cockatoo, long-billed',
      'Cockatoo, red-tailed',
      'Cockatoo, sulfur-crested',
      'Collared lemming',
      'Collared lizard',
      'Comb duck',
      'Common boubou shrike',
      'Common duiker',
      'Common eland',
      'Common goldeneye',
      'Common raccoon',
      'Common ringtail',
      'Common seal',
      'Common shelduck',
      'Common turkey',
      'Common wolf',
      'Common wombat',
      'Common zorro',
      'Constrictor, eastern boa',
      'Coot, red-knobbed',
      'Cormorant, flightless',
      'Cormorant, king',
      'Cormorant, large',
      'Cormorant, little',
      'Cormorant, pied',
      'Cougar',
      'Crab (unidentified)',
      'Crab, sally lightfoot',
      'Crane, stanley',
      'Crested bunting',
      'Crow, american',
      'Crow, pied',
      'Crowned hawk-eagle',
      'Curlew, black',
      'Currasow (unidentified)',
      'Curve-billed thrasher',
    ],
    'D': [
      'Dabchick',
      'Dama wallaby',
      'Dassie',
      'Deer, black-tailed',
      'Deer, red',
      'Deer, savannah',
      'Deer, swamp',
      'Deer, white-tailed',
      'Dingo',
      'Dog, black-tailed prairie',
      'Dove, emerald-spotted wood',
      'Dove, galapagos',
      'Dove, little brown',
      'Dove, ring',
      'Dove, rock',
      'Dragon, ornate rock',
      'Dragonfly, russian',
      'Drongo, fork-tailed',
      'Duck, blue',
      'Duck, comb',
      'Duck, mountain',
      'Duiker, gray',
      'Dusky gull',
    ],
    'E': [
      'Eagle owl (unidentified)',
      'Eagle, crowned',
      'Eastern fox squirrel',
      'Eastern white pelican',
      'Egret, cattle',
      'Egyptian goose',
      'Egyptian vulture',
      'Eland, common',
      'Elegant crested tinamou',
      'Emerald green tree boa',
      'Emerald-spotted wood dove',
      'Eurasian beaver',
      'Eurasian red squirrel',
      'European shelduck',
      'European wild cat',
    ],
    'F': [
      'Fairy penguin',
      'Falcon, peregrine',
      'Falcon, prairie',
      'Feral rock pigeon',
      'Flamingo, lesser',
      'Flamingo, roseat',
      'Flicker, campo',
      'Flicker, field',
      'Flycatcher, tyrant',
      'Flying fox (unidentified)',
      'Four-horned antelope',
      'Four-striped grass mouse',
      'Fox, arctic',
      'Fox, asian red',
      'Fox, cape',
      'Fox, north american red',
      'Frilled dragon',
      'Frilled lizard',
      'Fringe-eared oryx',
      'Frog (unidentified)',
    ],
    'G': [
      'Galah',
      'Galapagos albatross',
      'Galapagos mockingbird',
      'Gaur',
      'Gecko (unidentified)',
      'Gecko, barking',
      'Gecko, bent-toed',
      'Gecko, tokay',
      'Gemsbok',
      'Giraffe',
      'Glider, feathertail',
      'Glider, squirrel',
      'Glossy starling (unidentified)',
      'Goat, mountain',
      'Golden brush-tailed possum',
      'Golden eagle',
      'Golden-mantled ground squirrel',
      'Goose, andean',
      'Gorilla, western lowland',
      "Grant's gazelle",
      'Gray duiker',
      'Gray heron',
      'Gray rhea',
      'Great white pelican',
      'Greater blue-eared starling',
      'Greater roadrunner',
      'Green-winged trumpeter',
      'Grey lourie',
      'Grey phalarope',
      'Griffon vulture',
      'Grison',
      'Ground legaan',
      'Grouse, sage',
      'Gull, kelp',
      'Gull, lava',
      'Gull, southern black-backed',
      'Gull, swallow-tail',
    ],
    'H': [
      'Hare, arctic',
      "Hartebeest, coke's",
      'Hawk-headed parrot',
      'Hawk, red-tailed',
      'Hen, sage',
      'Heron, yellow-crowned night',
      'Hippopotamus',
      "Hoffman's sloth",
      'Hoopoe, eurasian',
      "Hornbill, leadbeateri's ground",
      'Hornbill, southern ground',
      'Hornbill, yellow-billed',
      'Horned lark',
      'Horned puffin',
      'House crow',
      'Huron',
      'Hyena, striped',
    ],
    'I': [
      'Ibis, glossy',
      'Ibis, puna',
      'Iguana, common green',
      'Indian giant squirrel',
      'Indian peacock',
      'Indian porcupine',
      'Indian red admiral',
      'Indian tree pie',
      'Insect, stick',
    ],
    'J': [
      'Jacana, african',
      'Jackal, black-backed',
      'Jackal, indian',
      'Jaguar',
      'Japanese macaque',
    ],
    'K': [
      'Kaffir cat',
      'Kafue flats lechwe',
      'Kangaroo, eastern grey',
      'Kangaroo, jungle',
      'Kangaroo, red',
      'Killer whale',
      'King cormorant',
      'King vulture',
      'Kite, black',
      'Koala',
    ],
    'L': [
      'Langur, common',
      'Lappet-faced vulture',
      'Lapwing, southern',
      'Laughing kookaburra',
      'Lava gull',
      'Least chipmunk',
      'Legaan, ground',
      'Lemur, brown',
      'Lemur, lesser mouse',
      'Leopard, indian',
      'Lesser double-collared sunbird',
      'Lilac-breasted roller',
      'Lion, australian sea',
      'Lion, mountain',
      'Lion, south american sea',
      'Little blue penguin',
      'Little cormorant',
      'Lizard (unidentified)',
      'Lizard, collared',
      'Lizard, giant girdled',
      'Lizard, goanna',
      'Long-billed cockatoo',
      'Long-crested hawk eagle',
      'Long-necked turtle',
      'Long-tailed jaeger',
      'Long-tailed skua',
      'Lorikeet, scaly-breasted',
      'Lourie, grey',
      'Lynx, african',
    ],
    'M': [
      'Macaque, pig-tailed',
      'Macaque, rhesus',
      'Macaw, blue and yellow',
      'Magellanic penguin',
      'Magnificent frigate bird',
      'Magpie, australian',
      'Magpie, black-backed',
      'Malachite kingfisher',
      'Mallard',
      'Mara',
      'Marmot, hoary',
      'Marshbird, brown and yellow',
      'Meerkat',
      'Mexican beaded lizard',
      "Miner's cat",
      'Mississippi alligator',
      'Moccasin, water',
      'Mockingbird, galapagos',
      'Mongoose, small indian',
      'Monitor, two-banded',
      'Mule deer',
      'Musk ox',
      'Mynah, indian',
    ],
    'N': [
      'Native cat',
      'Nighthawk, common',
      'Nine-banded armadillo',
      'North American red fox',
      "Nutcracker, clark's",
    ],
    'O': [
      'Olive baboon',
      'Onager',
      'Openbill stork',
      'Orca',
      'Ostrich',
      'Otter, canadian river',
      'Otter, cape clawless',
      'Otter, giant',
      'Owl, australian masked',
      'Owl, madagascar hawk',
      'Oystercatcher, blackish',
    ],
    'P': [
      'Painted stork',
      'Palm squirrel',
      'Pampa gray fox',
      'Paradoxure',
      'Parakeet, rose-ringed',
      'Peacock, blue',
      'Pelican, brown',
      'Pelican, great white',
      'Penguin, galapagos',
      'Phalarope, northern',
      'Pheasant, ring-necked',
      'Pie, indian tree',
      'Pied avocet',
      'Pied butcher bird',
      'Pied crow',
      'Pied kingfisher',
      'Pigeon, feral rock',
      'Plains zebra',
      'Plover, three-banded',
      'Porcupine, north american',
      'Porcupine, prehensile-tailed',
      'Possum, western pygmy',
      'Potoroo',
      'Prairie falcon',
      'Puma',
      'Puma, south american',
    ],
    'Q': [
      'Quoll, spotted-tailed',
    ],
    'R': [
      'Rabbit, eastern cottontail',
      'Raccoon, common',
      'Racer, american',
      'Rainbow lory',
      'Rat, white-faced tree',
      'Rattlesnake, eastern diamondback',
      'Red howler monkey',
      'Red lava crab',
      'Red phalarope',
      'Red sheep',
      'Red-billed hornbill',
      'Red-breasted cockatoo',
      'Red-capped cardinal',
      'Red-knobbed coot',
      'Red-necked phalarope',
      'Red-tailed wambenger',
      'Rhinoceros, black',
      'Rhinoceros, square-lipped',
      'Ring-necked pheasant',
      'Ring-tailed lemur',
      'Roan antelope',
      'Rock dove',
      'Roller, lilac-breasted',
      'Rufous-collared sparrow',
    ],
    'S': [
      'Sage grouse',
      'Sage hen',
      'Salmon, sockeye',
      'Sambar',
      'Sandgrouse, yellow-throated',
      'Sandhill crane',
      'Screamer, southern',
      'Sea birds (unidentified)',
      'Seal, northern fur',
      'Secretary bird',
      'Serval',
      'Seven-banded armadillo',
      'Sheep, red',
      'Shelduck, common',
      'Shelduck, european',
      'Shrike, common boubou',
      'Shrike, crimson-breasted',
      'Shrike, southern white-crowned',
      'Sidewinder',
      'Sloth, pale-throated three-toed',
      'Small-clawed otter',
      'Small-spotted genet',
      "Smith's bush squirrel",
      'Snake, racer',
      'Snake, western patch-nosed',
      'Snow goose',
      'Sociable weaver',
      'South American puma',
      'Southern boubou',
      'Southern elephant seal',
      'Southern hairy-nosed wombat',
      'Southern lapwing',
      'Southern sea lion',
      'Spotted deer',
      'Spotted-tailed quoll',
      'Springhare',
      'Spur-winged goose',
      'Spurfowl, yellow-necked',
      'Squirrel, arctic ground',
      'Squirrel, grey-footed',
      'Squirrel, pine',
      "Squirrel, richardson's ground",
      'Squirrel, thirteen-lined',
      'Squirrel, uinta ground',
      'Starling, greater blue-eared',
      'Starling, red-shouldered glossy',
      'Starling, superb',
      'Steenbuck',
      'Stork, black-necked',
      'Stork, painted',
      'Stork, woolly-necked',
      'Striated heron',
      'Striped dolphin',
      'Striped skunk',
      'Sugar glider',
      'Sun gazer',
      'Suricate',
      "Swainson's francolin",
      'Swallow (unidentified)',
      'Swamp deer',
    ],
    'T': [
      'Tailless tenrec',
      'Tapir, brazilian',
      'Tarantula, salmon pink bird eater',
      'Tasmanian devil',
      'Tawny frogmouth',
      'Tayra',
      'Teal, hottentot',
      'Tern, arctic',
      "Thomson's gazelle",
      'Thrasher, curve-billed',
      'Three-banded plover',
      'Toddy cat',
      'Topi',
      'Tortoise, asian foreset',
      'Tortoise, burmese brown mountain',
      'Tortoise, indian star',
      'Tortoise, radiated',
      'Toucan, red-billed',
      'Tree porcupine',
      'Trotter, lily',
      'Tsessebe',
      'Turkey, australian brush',
      'Turkey, common',
      'Turtle (unidentified)',
    ],
    'U': [
      'Uinta ground squirrel',
    ],
    'V': [
      'Vicuna',
      'Vine snake (unidentified)',
      'Violet-crested turaco',
      'Violet-eared waxbill',
      'Vulture, black',
      'Vulture, king',
      'Vulture, oriental white-backed',
      'Vulture, white-headed',
    ],
    'W': [
      'Wagtail, african pied',
      'Wallaby, agile',
      'Wallaby, dama',
      'Wapiti, elk,',
      'Wattled crane',
      'Waxbill, violet-eared',
      'Weaver, white-browed sparrow',
      'Western lowland gorilla',
      'Western spotted skunk',
      'Whale, baleen',
      'Whale, killer',
      'Whale, long-finned pilot',
      'White spoonbill',
      'White stork',
      'White-browed owl',
      'White-cheeked pintail',
      'White-faced tree rat',
      'White-fronted bee-eater',
      'White-fronted capuchin',
      'White-lipped peccary',
      'White-mantled colobus',
      'White-necked raven',
      'White-nosed coatimundi',
      'White-rumped vulture',
      'White-tailed deer',
      'White-throated kingfisher',
      'White-throated monitor',
      'White-throated robin',
      'White-winged dove',
      'White-winged tern',
      'Wildebeest, blue',
      'Wolf, common',
      'Wolf, mexican',
      'Wolf, timber',
      'Wombat, southern hairy-nosed',
      'Worm snake (unidentified)',
      'Woylie',
    ],
    'Y': [
      'Yak',
      'Yellow baboon',
      'Yellow-bellied marmot',
      'Yellow-headed caracara',
      'Yellow-throated sandgrouse',
    ],
    'Z': [
      'Zebra, plains',
      'Zorilla',
      'Zorro, common',
    ],
  };

  static const List<String> emojiHeaders = ['😀', '🐶', '🍏'];
  static const Map<String, List<String>> emojis = {
    '😀': [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '😂',
      '😊',
      '😇',
      '🙂',
      '🙃',
      '😉',
    ],
    '🐶': [
      '🐶',
      '🐱',
      '🐭',
      '🐹',
      '🐰',
      '🦊',
      '🐻',
      '🐼',
      '🐻',
      '‍❄',
      '️🐨',
      '🐯',
      '🦁',
      '🐮',
      '🐷',
      '🐽',
      '🐸',
      '🐵',
      '🙈',
      '🙉',
      '🙊',
    ],
    '🍏': [
      '🍏',
      '🍎',
      '🍐',
      '🍊',
      '🍋',
      '🍌',
      '🍉',
      '🍇',
      '🍓',
      '🫐',
      '🍈',
    ],
  };
}
